const movies = [
  // Acción
  {
    title: "Die Hard",
    director: "John McTiernan",
    year: 1988,
    genre: "Acción",
    rating: 9,
  },
  {
    title: "Mad Max: Fury Road",
    director: "George Miller",
    year: 2015,
    genre: "Acción",
    rating: 8.7,
  },
  {
    title: "John Wick",
    director: "Chad Stahelski",
    year: 2014,
    genre: "Acción",
    rating: 8.5,
  },
  {
    title: "Gladiator",
    director: "Ridley Scott",
    year: 2000,
    genre: "Acción",
    rating: 9,
  },
  {
    title: "The Dark Knight",
    director: "Christopher Nolan",
    year: 2008,
    genre: "Acción",
    rating: 9.5,
  },
  {
    title: "Terminator 2: Judgment Day",
    director: "James Cameron",
    year: 1991,
    genre: "Acción",
    rating: 9.2,
  },
  {
    title: "Inception",
    director: "Christopher Nolan",
    year: 2010,
    genre: "Acción",
    rating: 9.3,
  },
  {
    title: "Skyfall",
    director: "Sam Mendes",
    year: 2012,
    genre: "Acción",
    rating: 8,
  },

  // Comedia
  {
    title: "The Big Lebowski",
    director: "Joel Coen",
    year: 1998,
    genre: "Comedia",
    rating: 8.7,
  },
  {
    title: "Superbad",
    director: "Greg Mottola",
    year: 2007,
    genre: "Comedia",
    rating: 8.2,
  },
  {
    title: "Groundhog Day",
    director: "Harold Ramis",
    year: 1993,
    genre: "Comedia",
    rating: 8.6,
  },
  {
    title: "The Grand Budapest Hotel",
    director: "Wes Anderson",
    year: 2014,
    genre: "Comedia",
    rating: 9,
  },
  {
    title: "Monty Python and the Holy Grail",
    director: "Terry Gilliam, Terry Jones",
    year: 1975,
    genre: "Comedia",
    rating: 9.1,
  },
  {
    title: "Ghostbusters",
    director: "Ivan Reitman",
    year: 1984,
    genre: "Comedia",
    rating: 8.3,
  },
  {
    title: "Crazy, Stupid, Love.",
    director: "Glenn Ficarra, John Requa",
    year: 2011,
    genre: "Comedia",
    rating: 7.8,
  },
  {
    title: "Borat",
    director: "Larry Charles",
    year: 2006,
    genre: "Comedia",
    rating: 8,
  },

  // Drama
  {
    title: "The Shawshank Redemption",
    director: "Frank Darabont",
    year: 1994,
    genre: "Drama",
    rating: 9.8,
  },
  {
    title: "Forrest Gump",
    director: "Robert Zemeckis",
    year: 1994,
    genre: "Drama",
    rating: 9.5,
  },
  {
    title: "The Godfather",
    director: "Francis Ford Coppola",
    year: 1972,
    genre: "Drama",
    rating: 9.9,
  },
  {
    title: "Fight Club",
    director: "David Fincher",
    year: 1999,
    genre: "Drama",
    rating: 9.4,
  },
  {
    title: "Parasite",
    director: "Bong Joon-ho",
    year: 2019,
    genre: "Drama",
    rating: 9.6,
  },
  {
    title: "12 Angry Men",
    director: "Sidney Lumet",
    year: 1957,
    genre: "Drama",
    rating: 9.7,
  },
  {
    title: "Schindler’s List",
    director: "Steven Spielberg",
    year: 1993,
    genre: "Drama",
    rating: 9.8,
  },
  {
    title: "The Pursuit of Happyness",
    director: "Gabriele Muccino",
    year: 2006,
    genre: "Drama",
    rating: 8.8,
  },

  // Ciencia Ficción
  {
    title: "Blade Runner 2049",
    director: "Denis Villeneuve",
    year: 2017,
    genre: "Ciencia Ficción",
    rating: 9,
  },
  {
    title: "Interstellar",
    director: "Christopher Nolan",
    year: 2014,
    genre: "Ciencia Ficción",
    rating: 9.4,
  },
  {
    title: "The Matrix",
    director: "Lana y Lilly Wachowski",
    year: 1999,
    genre: "Ciencia Ficción",
    rating: 9.5,
  },
  {
    title: "Star Wars: Episode IV - A New Hope",
    director: "George Lucas",
    year: 1977,
    genre: "Ciencia Ficción",
    rating: 9.2,
  },
  {
    title: "Alien",
    director: "Ridley Scott",
    year: 1979,
    genre: "Ciencia Ficción",
    rating: 9,
  },
  {
    title: "Arrival",
    director: "Denis Villeneuve",
    year: 2016,
    genre: "Ciencia Ficción",
    rating: 8.9,
  },
  {
    title: "Ex Machina",
    director: "Alex Garland",
    year: 2014,
    genre: "Ciencia Ficción",
    rating: 8.6,
  },
  {
    title: "2001: A Space Odyssey",
    director: "Stanley Kubrick",
    year: 1968,
    genre: "Ciencia Ficción",
    rating: 9.3,
  },

  // Animación
  {
    title: "Toy Story",
    director: "John Lasseter",
    year: 1995,
    genre: "Animación",
    rating: 9,
  },
  {
    title: "Spirited Away",
    director: "Hayao Miyazaki",
    year: 2001,
    genre: "Animación",
    rating: 9.6,
  },
  {
    title: "Up",
    director: "Pete Docter",
    year: 2009,
    genre: "Animación",
    rating: 9,
  },
  {
    title: "Finding Nemo",
    director: "Andrew Stanton",
    year: 2003,
    genre: "Animación",
    rating: 8.8,
  },
  {
    title: "The Lion King",
    director: "Roger Allers, Rob Minkoff",
    year: 1994,
    genre: "Animación",
    rating: 9.4,
  },
  {
    title: "Coco",
    director: "Lee Unkrich, Adrian Molina",
    year: 2017,
    genre: "Animación",
    rating: 9.5,
  },
  {
    title: "Wall·E",
    director: "Andrew Stanton",
    year: 2008,
    genre: "Animación",
    rating: 9.2,
  },
  {
    title: "The Incredibles",
    director: "Brad Bird",
    year: 2004,
    genre: "Animación",
    rating: 8.9,
  },
];

module.exports = movies